name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main   # run only on push to main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: fatmehkassab/fatmehkassabproject:latest
